/**
 * Naive UI 主题覆盖配置（暖白轻刊）
 */
export const lightThemeOverrides = {
  common: {
    primaryColor: "#FE2C55",
    primaryColorHover: "#FF5A77",
    primaryColorPressed: "#E2244D",
    primaryColorSuppl: "#FF5A77",
    textColorBase: "#1A1412",
    textColor1: "#1A1412",
    textColor2: "#6E625C",
    textColor3: "#A89B93",
    bodyColor: "#FFF8F4",
    cardColor: "#FFFFFF",
    modalColor: "#FFFFFF",
    popoverColor: "#FFFFFF",
    tableColor: "#FFFFFF",
    borderColor: "#F2E5DF",
    dividerColor: "#F2E5DF",
    borderRadius: "16px",
    borderRadiusSmall: "10px",
  },
  Card: {
    color: "#FFFFFF",
    colorEmbedded: "#FFF0EB",
    borderColor: "#F2E5DF",
    borderRadius: "16px",
    titleTextColor: "#1A1412",
    textColor: "#1A1412",
  },
  Button: {
    borderRadiusMedium: "9999px",
    borderRadiusSmall: "9999px",
    borderRadiusTiny: "9999px",
    borderRadiusRound: "9999px",
    colorSecondary: "#FFF0EB",
    colorSecondaryHover: "#FFE9E2",
    colorSecondaryPressed: "#FFDFD5",
    textColorSecondary: "#1A1412",
  },
  Tag: {
    borderRadius: "9999px",
    color: "#FFF0EB",
    colorBorder: "transparent",
    textColor: "#6E625C",
  },
  Tabs: {
    tabTextColorActiveBar: "#FE2C55",
    tabTextColorHoverBar: "#FF5A77",
    barColor: "#FE2C55",
  },
  Pagination: {
    itemBorderRadius: "8px",
    itemColorHover: "#FFF0EB",
    itemColorActive: "#FE2C55",
    itemTextColorActive: "#FFFFFF",
  },
  Switch: {
    railColorActive: "#FE2C55",
  },
  Layout: {
    color: "transparent",
    colorEmbedded: "transparent",
  },
};

export const darkThemeOverrides = {
  common: {
    primaryColor: "#FE2C55",
    primaryColorHover: "#FF5A77",
    primaryColorPressed: "#E2244D",
    primaryColorSuppl: "#FF5A77",
    textColorBase: "#F6EFEA",
    textColor1: "#F6EFEA",
    textColor2: "#B7AAA2",
    textColor3: "#85786F",
    bodyColor: "#171311",
    cardColor: "#1F1A18",
    modalColor: "#26201D",
    popoverColor: "#26201D",
    tableColor: "#1F1A18",
    borderColor: "#352B26",
    dividerColor: "#352B26",
    borderRadius: "16px",
    borderRadiusSmall: "10px",
  },
  Card: {
    color: "#1F1A18",
    colorEmbedded: "#26201D",
    borderColor: "#352B26",
    borderRadius: "16px",
    titleTextColor: "#F6EFEA",
    textColor: "#F6EFEA",
  },
  Button: {
    borderRadiusMedium: "9999px",
    borderRadiusSmall: "9999px",
    borderRadiusTiny: "9999px",
    borderRadiusRound: "9999px",
    colorSecondary: "#26201D",
    colorSecondaryHover: "#2C2420",
    colorSecondaryPressed: "#352B26",
    textColorSecondary: "#F6EFEA",
  },
  Tag: {
    borderRadius: "9999px",
    color: "#26201D",
    colorBorder: "transparent",
    textColor: "#B7AAA2",
  },
  Tabs: {
    tabTextColorActiveBar: "#FE2C55",
    tabTextColorHoverBar: "#FF5A77",
    barColor: "#FE2C55",
  },
  Pagination: {
    itemBorderRadius: "8px",
    itemColorHover: "#26201D",
    itemColorActive: "#FE2C55",
    itemTextColorActive: "#FFFFFF",
  },
  Switch: {
    railColorActive: "#FE2C55",
  },
  Layout: {
    color: "transparent",
    colorEmbedded: "transparent",
  },
};
